/*
 * words.js — 難點字詞記憶卡 PWA 詞庫
 * v10 校對版（修正 v9 全域變數名稱，實際覆蓋 v8）
 *
 * 修訂條目（相對 v8 拼音）：
 *   難點詞語 02  #186 一株、#394 額頭、#401 寬容、#668 堤岸
 *   輕聲及兒化韻 02  #25 一個勁兒、#63 數不清
 *
 * 章節：
 *   難點詞語：931 條（原表 932，其中第 932 條為空白，已略去）
 *   輕聲及兒化韻：77 條
 *   高頻字詞：487 條（含多音字）
 *
 * 對接 index.html 所需的全域陣列：
 *   window.NORMAL_WORDS  — 難點詞語
 *   window.SPECIAL_WORDS — 輕聲及兒化韻（audioMode:"recording"）
 *   window.FREQ_WORDS    — 高頻字詞（note 顯示「多音字」等提示）
 */

window.NORMAL_WORDS = [
  { term: "臘月", pinyin: "là yuè" },
  { term: "初旬", pinyin: "chū xún" },
  { term: "開始", pinyin: "kāi shǐ" },
  { term: "展覽會", pinyin: "zhǎn lǎn huì" },
  { term: "蜜餞", pinyin: "mì jiàn" },
  { term: "氣象", pinyin: "qì xiàng" },
  { term: "黏", pinyin: "nián" },
  { term: "掃除", pinyin: "sǎo chú" },
  { term: "充足", pinyin: "chōng zú" },
  { term: "盼望", pinyin: "pàn wàng" },
  { term: "東風", pinyin: "dōng fēng" },
  { term: "腳步", pinyin: "jiǎo bù" },
  { term: "欣欣然", pinyin: "xīn xīn rán" },
  { term: "撫摸", pinyin: "fǔ mō" },
  { term: "氣息", pinyin: "qì xī" },
  { term: "微微", pinyin: "wēi wēi" },
  { term: "濕潤", pinyin: "shī rùn" },
  { term: "醞釀", pinyin: "yùn niàng" },
  { term: "巢", pinyin: "cháo" },
  { term: "宛轉", pinyin: "wǎn zhuǎn" },
  { term: "應和", pinyin: "yìng hè" },
  { term: "短笛", pinyin: "duǎn dí" },
  { term: "淙淙", pinyin: "cóng cóng" },
  { term: "湧流", pinyin: "yǒng liú" },
  { term: "尋常", pinyin: "xún cháng" },
  { term: "惱", pinyin: "nǎo" },
  { term: "薄煙", pinyin: "bó yān" },
  { term: "傍晚", pinyin: "bàng wǎn" },
  { term: "黃暈", pinyin: "huáng yùn" },
  { term: "烘托", pinyin: "hōng tuō" },
  { term: "蓑", pinyin: "suō" },
  { term: "笠", pinyin: "lì" },
  { term: "瞧去", pinyin: "qiáo qù" },
  { term: "朗潤", pinyin: "lǎng rùn" },
  { term: "枯", pinyin: "kū" },
  { term: "復返", pinyin: "fù fǎn" },
  { term: "儘管", pinyin: "jǐn guǎn" },
  { term: "斜斜", pinyin: "xié xié" },
  { term: "挪移", pinyin: "nuó yí" },
  { term: "旋轉", pinyin: "xuán zhuǎn" },
  { term: "水盆", pinyin: "shuǐ pén" },
  { term: "凝然", pinyin: "níng rán" },
  { term: "覺察", pinyin: "jué chá" },
  { term: "遮挽", pinyin: "zhē wǎn" },
  { term: "跨過", pinyin: "kuà guò" },
  { term: "溜走", pinyin: "liū zǒu" },
  { term: "掩", pinyin: "yǎn" },
  { term: "徘徊", pinyin: "pái huái" },
  { term: "薄霧", pinyin: "bó wù" },
  { term: "吹散", pinyin: "chuī sàn" },
  { term: "蒸融", pinyin: "zhēng róng" },
  { term: "痕跡", pinyin: "hén jì" },
  { term: "赤裸裸", pinyin: "chì luǒ luǒ" },
  { term: "茫茫然", pinyin: "máng máng rán" },
  { term: "耐性", pinyin: "nài xìng" },
  { term: "韌性", pinyin: "rèn xìng" },
  { term: "一旦", pinyin: "yī dàn" },
  { term: "懷疑", pinyin: "huái yí" },
  { term: "研究", pinyin: "yán jiū" },
  { term: "其實", pinyin: "qí shí" },
  { term: "科學", pinyin: "kē xué" },
  { term: "仰慕不已", pinyin: "yǎng mù bù yǐ" },
  { term: "信手拈來", pinyin: "xìn shǒu niān lái" },
  { term: "甚至", pinyin: "shèn zhì" },
  { term: "攻克", pinyin: "gōng kè" },
  { term: "堡壘", pinyin: "bǎo lěi" },
  { term: "氣餒", pinyin: "qì něi" },
  { term: "岔路", pinyin: "chà lù" },
  { term: "不要緊", pinyin: "bù yào jǐn" },
  { term: "善於", pinyin: "shàn yú" },
  { term: "經驗", pinyin: "jīng yàn" },
  { term: "繼續", pinyin: "jì xù" },
  { term: "根據", pinyin: "gēn jù" },
  { term: "體會", pinyin: "tǐ huì" },
  { term: "堅持", pinyin: "jiān chí" },
  { term: "天分", pinyin: "tiān fèn" },
  { term: "勞作", pinyin: "láo zuò" },
  { term: "形式", pinyin: "xíng shì" },
  { term: "百年", pinyin: "bǎi nián" },
  { term: "滑輪", pinyin: "huá lún" },
  { term: "修繕", pinyin: "xiū shàn" },
  { term: "尊重", pinyin: "zūn zhòng" },
  { term: "形制", pinyin: "xíng zhì" },
  { term: "技術", pinyin: "jì shù" },
  { term: "開荒料", pinyin: "kāi huāng liào" },
  { term: "墨斗", pinyin: "mò dǒu" },
  { term: "杖竿", pinyin: "zhàng gān" },
  { term: "錛", pinyin: "bēn" },
  { term: "鑿", pinyin: "záo" },
  { term: "斧", pinyin: "fǔ" },
  { term: "鋸", pinyin: "jù" },
  { term: "刨", pinyin: "bào" },
  { term: "瓦作", pinyin: "wǎ zuò" },
  { term: "苫背", pinyin: "shàn bèi" },
  { term: "口訣", pinyin: "kǒu jué" },
  { term: "硬度", pinyin: "yìng dù" },
  { term: "符合", pinyin: "fú hé" },
  { term: "疏漏", pinyin: "shū lòu" },
  { term: "導致", pinyin: "dǎo zhì" },
  { term: "損壞", pinyin: "sǔn huài" },
  { term: "致命", pinyin: "zhì mìng" },
  { term: "殷墟", pinyin: "yīn xū" },
  { term: "甲骨卜辭", pinyin: "jiǎ gǔ bǔ cí" },
  { term: "春秋左傳", pinyin: "chūn qiū zuǒ zhuàn" },
  { term: "諸侯", pinyin: "zhū hóu" },
  { term: "掌管", pinyin: "zhǎng guǎn" },
  { term: "營造", pinyin: "yíng zào" },
  { term: "名工巧匠", pinyin: "míng gōng qiǎo jiàng" },
  { term: "宏偉", pinyin: "hóng wěi" },
  { term: "記載", pinyin: "jì zǎi" },
  { term: "立春", pinyin: "lì chūn" },
  { term: "漸漸", pinyin: "jiàn jiàn" },
  { term: "融化", pinyin: "róng huà" },
  { term: "萌發", pinyin: "méng fā" },
  { term: "次第", pinyin: "cì dì" },
  { term: "翩然", pinyin: "piān rán" },
  { term: "布穀鳥", pinyin: "bù gǔ niǎo" },
  { term: "炎熱", pinyin: "yán rè" },
  { term: "植物", pinyin: "zhí wù" },
  { term: "孕育", pinyin: "yùn yù" },
  { term: "時期", pinyin: "shí qī" },
  { term: "成熟", pinyin: "chéng shú" },
  { term: "北雁", pinyin: "běi yàn" },
  { term: "活躍", pinyin: "huó yuè" },
  { term: "銷聲匿跡", pinyin: "xiāo shēng nì jì" },
  { term: "呈現", pinyin: "chéng xiàn" },
  { term: "衰草連天", pinyin: "shuāi cǎo lián tiān" },
  { term: "風雪載途", pinyin: "fēng xuě zài tú" },
  { term: "亞熱帶", pinyin: "yà rè dài" },
  { term: "區域", pinyin: "qū yù" },
  { term: "草木榮枯", pinyin: "cǎo mù róng kū" },
  { term: "大自然", pinyin: "dà zì rán" },
  { term: "耕地", pinyin: "gēng dì" },
  { term: "割麥插禾", pinyin: "gē mài chā hé" },
  { term: "草長鶯飛", pinyin: "cǎo zhǎng yīng fēi" },
  { term: "現象", pinyin: "xiàn xiàng" },
  { term: "物候", pinyin: "wù hòu" },
  { term: "養育", pinyin: "yǎng yù" },
  { term: "時節", pinyin: "shí jié" },
  { term: "高速列車", pinyin: "gāo sù liè chē" },
  { term: "轉瞬即逝", pinyin: "zhuǎn shùn jí shì" },
  { term: "不得不", pinyin: "bù dé bù" },
  { term: "司機", pinyin: "sī jī" },
  { term: "時速", pinyin: "shí sù" },
  { term: "能見度", pinyin: "néng jiàn dù" },
  { term: "霧霾", pinyin: "wù mái" },
  { term: "識別", pinyin: "shí bié" },
  { term: "肉眼", pinyin: "ròu yǎn" },
  { term: "障礙", pinyin: "zhàng ài" },
  { term: "設置", pinyin: "shè zhì" },
  { term: "信號", pinyin: "xìn hào" },
  { term: "列控系統", pinyin: "liè kòng xì tǒng" },
  { term: "實現", pinyin: "shí xiàn" },
  { term: "傳輸", pinyin: "chuán shū" },
  { term: "計算機", pinyin: "jì suàn jī" },
  { term: "間隔", pinyin: "jiàn gé" },
  { term: "追蹤", pinyin: "zhuī zōng" },
  { term: "確保", pinyin: "què bǎo" },
  { term: "仍然", pinyin: "réng rán" },
  { term: "軌道", pinyin: "guǐ dào" },
  { term: "傳說", pinyin: "chuán shuō" },
  { term: "現實", pinyin: "xiàn shí" },
  { term: "沿線", pinyin: "yán xiàn" },
  { term: "攝像頭", pinyin: "shè xiàng tóu" },
  { term: "肇慶市", pinyin: "zhào qìng shì" },
  { term: "驅車", pinyin: "qū chē" },
  { term: "東郊", pinyin: "dōng jiāo" },
  { term: "鼎湖山", pinyin: "dǐng hú shān" },
  { term: "籠罩", pinyin: "lǒng zhào" },
  { term: "寒翠橋", pinyin: "hán cuì qiáo" },
  { term: "草豐林茂", pinyin: "cǎo fēng lín mào" },
  { term: "交錯流瀉", pinyin: "jiāo cuò liú xiè" },
  { term: "踮腳", pinyin: "diǎn jiǎo" },
  { term: "跳躍", pinyin: "tiào yuè" },
  { term: "愈", pinyin: "yù" },
  { term: "猶如", pinyin: "yóu rú" },
  { term: "忽然", pinyin: "hū rán" },
  { term: "山鳴谷應", pinyin: "shān míng gǔ yìng" },
  { term: "安詳厚重", pinyin: "ān xiáng hòu zhòng" },
  { term: "寧靜", pinyin: "níng jìng" },
  { term: "循", pinyin: "xún" },
  { term: "慶雲寺", pinyin: "qìng yún sì" },
  { term: "規模", pinyin: "guī mó" },
  { term: "宏大", pinyin: "hóng dà" },
  { term: "古剎", pinyin: "gǔ chà" },
  { term: "一株", pinyin: "yī zhū" },
  { term: "決定", pinyin: "jué dìng" },
  { term: "借宿", pinyin: "jiè sù" },
  { term: "萬籟俱寂", pinyin: "wàn lài jù jì" },
  { term: "枕邊", pinyin: "zhěn biān" },
  { term: "辨識", pinyin: "biàn shí" },
  { term: "輕柔", pinyin: "qīng róu" },
  { term: "流淌", pinyin: "liú tǎng" },
  { term: "世間", pinyin: "shì jiān" },
  { term: "幸福", pinyin: "xìng fú" },
  { term: "擁有", pinyin: "yōng yǒu" },
  { term: "浩瀚", pinyin: "hào hàn" },
  { term: "豐富", pinyin: "fēng fù" },
  { term: "我想", pinyin: "wǒ xiǎng" },
  { term: "那些", pinyin: "nà xiē" },
  { term: "喪失", pinyin: "sàng shī" },
  { term: "補償", pinyin: "bǔ cháng" },
  { term: "體現", pinyin: "tǐ xiàn" },
  { term: "欣悅", pinyin: "xīn yuè" },
  { term: "苦難", pinyin: "kǔ nàn" },
  { term: "關於", pinyin: "guān yú" },
  { term: "無形間", pinyin: "wú xíng jiān" },
  { term: "無限", pinyin: "wú xiàn" },
  { term: "草木", pinyin: "cǎo mù" },
  { term: "上溯", pinyin: "shàng sù" },
  { term: "存在", pinyin: "cún zài" },
  { term: "奇風異俗", pinyin: "qí fēng yì sú" },
  { term: "加惠於", pinyin: "jiā huì yú" },
  { term: "陶冶", pinyin: "táo yě" },
  { term: "往哲先賢", pinyin: "wǎng zhé xiān xián" },
  { term: "著述", pinyin: "zhù shù" },
  { term: "智慧", pinyin: "zhì huì" },
  { term: "家鄉", pinyin: "jiā xiāng" },
  { term: "庭院", pinyin: "tíng yuàn" },
  { term: "納涼", pinyin: "nà liáng" },
  { term: "繁星", pinyin: "fán xīng" },
  { term: "彷彿", pinyin: "fǎng fú" },
  { term: "星群密布", pinyin: "xīng qún mì bù" },
  { term: "微小", pinyin: "wēi xiǎo" },
  { term: "無處不在", pinyin: "wú chù bù zài" },
  { term: "如今", pinyin: "rú jīn" },
  { term: "艙面", pinyin: "cāng miàn" },
  { term: "懸", pinyin: "xuán" },
  { term: "半明半昧", pinyin: "bàn míng bàn mèi" },
  { term: "搖搖欲墜", pinyin: "yáo yáo yù zhuì" },
  { term: "無數", pinyin: "wú shù" },
  { term: "飛舞", pinyin: "fēi wǔ" },
  { term: "柔和", pinyin: "róu hé" },
  { term: "夢幻", pinyin: "mèng huàn" },
  { term: "眨眼", pinyin: "zhǎ yǎn" },
  { term: "忘記", pinyin: "wàng jì" },
  { term: "微笑", pinyin: "wēi xiào" },
  { term: "哥倫波", pinyin: "gē lún bō" },
  { term: "自古以來", pinyin: "zì gǔ yǐ lái" },
  { term: "農曆", pinyin: "nóng lì" },
  { term: "鹽官鎮", pinyin: "yán guān zhèn" },
  { term: "據說", pinyin: "jù shuō" },
  { term: "隨", pinyin: "suí" },
  { term: "海塘大堤", pinyin: "hǎi táng dà dī" },
  { term: "寬闊", pinyin: "kuān kuò" },
  { term: "橫臥", pinyin: "héng wò" },
  { term: "鎮海古塔", pinyin: "zhèn hǎi gǔ tǎ" },
  { term: "屹立", pinyin: "yì lì" },
  { term: "雲霧", pinyin: "yún wù" },
  { term: "若隱若現", pinyin: "ruò yǐn ruò xiàn" },
  { term: "昂首東望", pinyin: "áng shǒu dōng wàng" },
  { term: "悶雷滾動", pinyin: "mèn léi gǔn dòng" },
  { term: "人聲鼎沸", pinyin: "rén shēng dǐng fèi" },
  { term: "沸騰", pinyin: "fèi téng" },
  { term: "橫貫江面", pinyin: "héng guàn jiāng miàn" },
  { term: "一堵", pinyin: "yī dǔ" },
  { term: "浩浩蕩蕩", pinyin: "hào hào dàng dàng" },
  { term: "顫動", pinyin: "chàn dòng" },
  { term: "霎時", pinyin: "shà shí" },
  { term: "奔騰", pinyin: "bēn téng" },
  { term: "漫天捲地", pinyin: "màn tiān juǎn dì" },
  { term: "湧來", pinyin: "yǒng lái" },
  { term: "風號浪吼", pinyin: "fēng háo làng hǒu" },
  { term: "恢復", pinyin: "huī fù" },
  { term: "枯黃", pinyin: "kū huáng" },
  { term: "嘎吱嘎吱", pinyin: "gā zhī gā zhī" },
  { term: "光禿禿", pinyin: "guāng tū tū" },
  { term: "描摹", pinyin: "miáo mó" },
  { term: "殘酷", pinyin: "cán kù" },
  { term: "荒涼", pinyin: "huāng liáng" },
  { term: "出乎", pinyin: "chū hū" },
  { term: "這", pinyin: "zhè" },
  { term: "何嘗", pinyin: "hé cháng" },
  { term: "敗柳殘荷", pinyin: "bài liǔ cán hé" },
  { term: "突然", pinyin: "tū rán" },
  { term: "仰向", pinyin: "yǎng xiàng" },
  { term: "怔住", pinyin: "zhèng zhù" },
  { term: "均衡", pinyin: "jūn héng" },
  { term: "嗅", pinyin: "xiù" },
  { term: "夕陽", pinyin: "xī yáng" },
  { term: "燃燒", pinyin: "rán shāo" },
  { term: "橘紅色", pinyin: "jú hóng sè" },
  { term: "晚霞", pinyin: "wǎn xiá" },
  { term: "染成", pinyin: "rǎn chéng" },
  { term: "壯觀", pinyin: "zhuàng guān" },
  { term: "湧起", pinyin: "yǒng qǐ" },
  { term: "映照", pinyin: "yìng zhào" },
  { term: "霍霍燃燒", pinyin: "huò huò rán shāo" },
  { term: "閃爍", pinyin: "shǎn shuò" },
  { term: "滾動", pinyin: "gǔn dòng" },
  { term: "緋紅", pinyin: "fēi hóng" },
  { term: "肅穆", pinyin: "sù mù" },
  { term: "廣漠", pinyin: "guǎng mò" },
  { term: "放射", pinyin: "fàng shè" },
  { term: "光輝", pinyin: "guāng huī" },
  { term: "一盞", pinyin: "yī zhǎn" },
  { term: "懸掛", pinyin: "xuán guà" },
  { term: "倒映", pinyin: "dào yìng" },
  { term: "晃動", pinyin: "huàng dòng" },
  { term: "蒼穹", pinyin: "cāng qióng" },
  { term: "輝映", pinyin: "huī yìng" },
  { term: "軟綿綿", pinyin: "ruǎn mián mián" },
  { term: "細軟", pinyin: "xì ruǎn" },
  { term: "溫柔", pinyin: "wēn róu" },
  { term: "誕生", pinyin: "dàn shēng" },
  { term: "偶然", pinyin: "ǒu rán" },
  { term: "性質", pinyin: "xìng zhì" },
  { term: "原始", pinyin: "yuán shǐ" },
  { term: "組成", pinyin: "zǔ chéng" },
  { term: "組織", pinyin: "zǔ zhī" },
  { term: "新陳代謝", pinyin: "xīn chén dài xiè" },
  { term: "媒介", pinyin: "méi jiè" },
  { term: "危險", pinyin: "wēi xiǎn" },
  { term: "脆弱", pinyin: "cuì ruò" },
  { term: "舉足輕重", pinyin: "jǔ zú qīng zhòng" },
  { term: "缺水之憂", pinyin: "quē shuǐ zhī yōu" },
  { term: "溶劑", pinyin: "róng jì" },
  { term: "許多", pinyin: "xǔ duō" },
  { term: "必須", pinyin: "bì xū" },
  { term: "氯化鈉", pinyin: "lǜ huà nà" },
  { term: "氯化鉀", pinyin: "lǜ huà jiǎ" },
  { term: "碳酸鹽", pinyin: "tàn suān yán" },
  { term: "磷酸鹽", pinyin: "lín suān yán" },
  { term: "溶解氧", pinyin: "róng jiě yǎng" },
  { term: "吸取", pinyin: "xī qǔ" },
  { term: "熱容量", pinyin: "rè róng liàng" },
  { term: "任憑", pinyin: "rèn píng" },
  { term: "烈日", pinyin: "liè rì" },
  { term: "曝曬", pinyin: "pù shài" },
  { term: "掃蕩", pinyin: "sǎo dàng" },
  { term: "溫度", pinyin: "wēn dù" },
  { term: "雖然", pinyin: "suī rán" },
  { term: "扼殺", pinyin: "è shā" },
  { term: "屏障", pinyin: "píng zhàng" },
  { term: "發展", pinyin: "fā zhǎn" },
  { term: "必要", pinyin: "bì yào" },
  { term: "歷史", pinyin: "lì shǐ" },
  { term: "都城", pinyin: "dū chéng" },
  { term: "密集區", pinyin: "mì jí qū" },
  { term: "盆地", pinyin: "pén dì" },
  { term: "王朝", pinyin: "wáng cháo" },
  { term: "構成", pinyin: "gòu chéng" },
  { term: "早期", pinyin: "zǎo qī" },
  { term: "華夏", pinyin: "huá xià" },
  { term: "促成", pinyin: "cù chéng" },
  { term: "自然", pinyin: "zì rán" },
  { term: "南部", pinyin: "nán bù" },
  { term: "土壤", pinyin: "tǔ rǎng" },
  { term: "旱作", pinyin: "hàn zuò" },
  { term: "需求", pinyin: "xū qiú" },
  { term: "農作物", pinyin: "nóng zuò wù" },
  { term: "粟", pinyin: "sù" },
  { term: "黍", pinyin: "shǔ" },
  { term: "種植", pinyin: "zhòng zhí" },
  { term: "提供", pinyin: "tí gōng" },
  { term: "得天獨厚", pinyin: "dé tiān dú hòu" },
  { term: "社會", pinyin: "shè huì" },
  { term: "形勢圖", pinyin: "xíng shì tú" },
  { term: "軸心", pinyin: "zhóu xīn" },
  { term: "處於", pinyin: "chǔ yú" },
  { term: "證據", pinyin: "zhèng jù" },
  { term: "恰恰", pinyin: "qià qià" },
  { term: "寬廣", pinyin: "kuān guǎng" },
  { term: "火車", pinyin: "huǒ chē" },
  { term: "故鄉", pinyin: "gù xiāng" },
  { term: "非同尋常", pinyin: "fēi tóng xún cháng" },
  { term: "即便", pinyin: "jí biàn" },
  { term: "或許", pinyin: "huò xǔ" },
  { term: "熙攘", pinyin: "xī rǎng" },
  { term: "匆忙", pinyin: "cōng máng" },
  { term: "湧動", pinyin: "yǒng dòng" },
  { term: "一刹那", pinyin: "yī chà nà" },
  { term: "況且", pinyin: "kuàng qiě" },
  { term: "陡然", pinyin: "dǒu rán" },
  { term: "鐵軌", pinyin: "tiě guǐ" },
  { term: "瀰漫", pinyin: "mí màn" },
  { term: "溫暖", pinyin: "wēn nuǎn" },
  { term: "懷抱", pinyin: "huái bào" },
  { term: "傳統", pinyin: "chuán tǒng" },
  { term: "團聚", pinyin: "tuán jù" },
  { term: "提升", pinyin: "tí shēng" },
  { term: "延伸", pinyin: "yán shēn" },
  { term: "老百姓", pinyin: "lǎo bǎi xìng" },
  { term: "天南地北", pinyin: "tiān nán dì běi" },
  { term: "三山五嶽", pinyin: "sān shān wǔ yuè" },
  { term: "商店", pinyin: "shāng diàn" },
  { term: "沉重", pinyin: "chén zhòng" },
  { term: "年龄", pinyin: "nián líng" },
  { term: "患病", pinyin: "huàn bìng" },
  { term: "输液", pinyin: "shū yè" },
  { term: "扎", pinyin: "zhā" },
  { term: "血管", pinyin: "xuè guǎn" },
  { term: "抱怨", pinyin: "bào yuàn" },
  { term: "額頭", pinyin: "é tóu" },
  { term: "不禁", pinyin: "bù jīn" },
  { term: "涌", pinyin: "yǒng" },
  { term: "實習", pinyin: "shí xí" },
  { term: "扎針", pinyin: "zhā zhēn" },
  { term: "鼓勵", pinyin: "gǔ lì" },
  { term: "患者", pinyin: "huàn zhě" },
  { term: "寬容", pinyin: "kuān róng" },
  { term: "温暖", pinyin: "wēn nuǎn" },
  { term: "將心比心", pinyin: "jiāng xīn bǐ xīn" },
  { term: "晉祠", pinyin: "jìn cí" },
  { term: "巍巍", pinyin: "wēi wēi" },
  { term: "層層疊疊", pinyin: "céng céng dié dié" },
  { term: "萬山叢中", pinyin: "wàn shān cóng zhōng" },
  { term: "點染", pinyin: "diǎn rǎn" },
  { term: "極其", pinyin: "jí qí" },
  { term: "呂祖殿", pinyin: "lǚ zǔ diàn" },
  { term: "明塑", pinyin: "míng sù" },
  { term: "呂洞賓", pinyin: "lǚ dòng bīn" },
  { term: "姿態神情", pinyin: "zī tài shén qíng" },
  { term: "脫口讚嘆", pinyin: "tuō kǒu zàn tàn" },
  { term: "綠陰森森", pinyin: "lǜ yīn sēn sēn" },
  { term: "柏洞", pinyin: "bǎi dòng" },
  { term: "露面", pinyin: "lòu miàn" },
  { term: "對松山", pinyin: "duì sōng shān" },
  { term: "對峙", pinyin: "duì zhì" },
  { term: "年紀", pinyin: "nián jì" },
  { term: "濃", pinyin: "nóng" },
  { term: "權當", pinyin: "quán dàng" },
  { term: "黑幕", pinyin: "hēi mù" },
  { term: "宇宙", pinyin: "yǔ zhòu" },
  { term: "舞台", pinyin: "wǔ tái" },
  { term: "中央", pinyin: "zhōng yāng" },
  { term: "大明星", pinyin: "dà míng xīng" },
  { term: "渾身", pinyin: "hún shēn" },
  { term: "奪人心魄", pinyin: "duó rén xīn pò" },
  { term: "光芒", pinyin: "guāng máng" },
  { term: "披", pinyin: "pī" },
  { term: "如同", pinyin: "rú tóng" },
  { term: "緩緩飛行", pinyin: "huǎn huǎn fēi xíng" },
  { term: "覆蓋", pinyin: "fù gài" },
  { term: "蔚藍色", pinyin: "wèi lán sè" },
  { term: "驕傲", pinyin: "jiāo ào" },
  { term: "廣闊壯觀", pinyin: "guǎng kuò zhuàng guān" },
  { term: "黃綠相間", pinyin: "huáng lǜ xiāng jiàn" },
  { term: "陸地", pinyin: "lù dì" },
  { term: "縱橫其間", pinyin: "zòng héng qí jiān" },
  { term: "曼妙", pinyin: "màn miào" },
  { term: "緩緩駛來", pinyin: "huǎn huǎn shǐ lái" },
  { term: "緩緩離去", pinyin: "huǎn huǎn lí qù" },
  { term: "完全", pinyin: "wán quán" },
  { term: "足以", pinyin: "zú yǐ" },
  { term: "震撼", pinyin: "zhèn hàn" },
  { term: "廣袤", pinyin: "guǎng mào" },
  { term: "作為", pinyin: "zuò wéi" },
  { term: "中華民族", pinyin: "zhōng huá mín zú" },
  { term: "塵埃", pinyin: "chén āi" },
  { term: "獨自", pinyin: "dú zì" },
  { term: "此刻", pinyin: "cǐ kè" },
  { term: "難忘", pinyin: "nán wàng" },
  { term: "女教師", pinyin: "nǚ jiào shī" },
  { term: "榆錢", pinyin: "yú qián" },
  { term: "黑痣", pinyin: "hēi zhì" },
  { term: "僅僅", pinyin: "jǐn jǐn" },
  { term: "教鞭", pinyin: "jiào biān" },
  { term: "迎", pinyin: "yíng" },
  { term: "狡猾", pinyin: "jiǎo huá" },
  { term: "察覺", pinyin: "chá jué" },
  { term: "善於觀察", pinyin: "shàn yú guān chá" },
  { term: "表演", pinyin: "biǎo yǎn" },
  { term: "跳舞", pinyin: "tiào wǔ" },
  { term: "背誦", pinyin: "bèi sòng" },
  { term: "孤舟", pinyin: "gū zhōu" },
  { term: "雲頭", pinyin: "yún tóu" },
  { term: "海鷗", pinyin: "hǎi ōu" },
  { term: "愛好", pinyin: "ài hào" },
  { term: "文學", pinyin: "wén xué" },
  { term: "影響", pinyin: "yǐng xiǎng" },
  { term: "寫字", pinyin: "xiě zì" },
  { term: "出發", pinyin: "chū fā" },
  { term: "屬於", pinyin: "shǔ yú" },
  { term: "哪怕", pinyin: "nǎ pà" },
  { term: "山再青", pinyin: "shān zài qīng" },
  { term: "水再秀", pinyin: "shuǐ zài xiù" },
  { term: "羈絆", pinyin: "jī bàn" },
  { term: "雙腳", pinyin: "shuāng jiǎo" },
  { term: "巍峨", pinyin: "wēi é" },
  { term: "遺憾", pinyin: "yí hàn" },
  { term: "依舊", pinyin: "yī jiù" },
  { term: "神秘", pinyin: "shén mì" },
  { term: "坎坷", pinyin: "kǎn kě" },
  { term: "浪濤", pinyin: "làng tāo" },
  { term: "風沙", pinyin: "fēng shā" },
  { term: "猛獸", pinyin: "měng shòu" },
  { term: "景致", pinyin: "jǐng zhì" },
  { term: "慶幸", pinyin: "qìng xìng" },
  { term: "老當益壯", pinyin: "lǎo dāng yì zhuàng" },
  { term: "學習", pinyin: "xué xí" },
  { term: "深刻", pinyin: "shēn kè" },
  { term: "勇敢", pinyin: "yǒng gǎn" },
  { term: "沉著", pinyin: "chén zhuó" },
  { term: "機敏", pinyin: "jī mǐn" },
  { term: "品味", pinyin: "pǐn wèi" },
  { term: "繽紛", pinyin: "bīn fēn" },
  { term: "人生", pinyin: "rén shēng" },
  { term: "志向", pinyin: "zhì xiàng" },
  { term: "意志", pinyin: "yì zhì" },
  { term: "青春", pinyin: "qīng chūn" },
  { term: "熱血", pinyin: "rè xuè" },
  { term: "高遠", pinyin: "gāo yuǎn" },
  { term: "目標", pinyin: "mù biāo" },
  { term: "爭取", pinyin: "zhēng qǔ" },
  { term: "光榮", pinyin: "guāng róng" },
  { term: "境界", pinyin: "jìng jiè" },
  { term: "屋前", pinyin: "wū qián" },
  { term: "或", pinyin: "huò" },
  { term: "絲瓜", pinyin: "sī guā" },
  { term: "瓜藤", pinyin: "guā téng" },
  { term: "攀上", pinyin: "pān shàng" },
  { term: "棚架", pinyin: "péng jià" },
  { term: "屋簷", pinyin: "wū yán" },
  { term: "結出", pinyin: "jiē chū" },
  { term: "別有風趣", pinyin: "bié yǒu fēng qù" },
  { term: "裝飾", pinyin: "zhuāng shì" },
  { term: "高樓", pinyin: "gāo lóu" },
  { term: "蹲", pinyin: "dūn" },
  { term: "旗桿", pinyin: "qí gān" },
  { term: "幾株花", pinyin: "jǐ zhū huā" },
  { term: "雞冠花", pinyin: "jī guān huā" },
  { term: "順序", pinyin: "shùn xù" },
  { term: "樸素", pinyin: "pǔ sù" },
  { term: "獨特", pinyin: "dú tè" },
  { term: "竹", pinyin: "zhú" },
  { term: "趕", pinyin: "gǎn" },
  { term: "綠蔭", pinyin: "lǜ yīn" },
  { term: "幾場春雨", pinyin: "jǐ cháng chūn yǔ" },
  { term: "鮮嫩", pinyin: "xiān nèn" },
  { term: "筍", pinyin: "sǔn" },
  { term: "成群", pinyin: "chéng qún" },
  { term: "照例", pinyin: "zhào lì" },
  { term: "肯定", pinyin: "kěn dìng" },
  { term: "瞧見", pinyin: "qiáo jiàn" },
  { term: "母雞", pinyin: "mǔ jī" },
  { term: "率領", pinyin: "shuài lǐng" },
  { term: "覓食", pinyin: "mì shí" },
  { term: "聳", pinyin: "sǒng" },
  { term: "大踏步", pinyin: "dà tà bù" },
  { term: "倘若", pinyin: "tǎng ruò" },
  { term: "扎到", pinyin: "zhā dào" },
  { term: "即使", pinyin: "jí shǐ" },
  { term: "附近", pinyin: "fù jìn" },
  { term: "婦女", pinyin: "fù nǚ" },
  { term: "搗衣", pinyin: "dǎo yī" },
  { term: "吃驚", pinyin: "chī jīng" },
  { term: "若是", pinyin: "ruò shì" },
  { term: "逼近", pinyin: "bī jìn" },
  { term: "榕樹", pinyin: "róng shù" },
  { term: "丫枝", pinyin: "yā zhī" },
  { term: "垂到", pinyin: "chuí dào" },
  { term: "遠處", pinyin: "yuǎn chù" },
  { term: "斜躺", pinyin: "xié tǎng" },
  { term: "枝繁葉茂", pinyin: "zhī fán yè mào" },
  { term: "全部", pinyin: "quán bù" },
  { term: "展示", pinyin: "zhǎn shì" },
  { term: "一簇", pinyin: "yī cù" },
  { term: "縫隙", pinyin: "fèng xì" },
  { term: "翠綠", pinyin: "cuì lǜ" },
  { term: "閃耀", pinyin: "shǎn yào" },
  { term: "似乎", pinyin: "sì hū" },
  { term: "做窩", pinyin: "zuò wō" },
  { term: "捉", pinyin: "zhuō" },
  { term: "撲翅", pinyin: "pū chì" },
  { term: "木樁", pinyin: "mù zhuāng" },
  { term: "漲潮", pinyin: "zhǎng cháo" },
  { term: "這樣", pinyin: "zhè yàng" },
  { term: "緩緩", pinyin: "huǎn huǎn" },
  { term: "樹梢", pinyin: "shù shāo" },
  { term: "科學家", pinyin: "kē xué jiā" },
  { term: "橫七豎八", pinyin: "héng qī shù bā" },
  { term: "繫", pinyin: "jì" },
  { term: "蝙蝠", pinyin: "biān fú" },
  { term: "沒碰着", pinyin: "méi pèng zháo" },
  { term: "到處亂撞", pinyin: "dào chù luàn zhuàng" },
  { term: "證明", pinyin: "zhèng míng" },
  { term: "配合", pinyin: "pèi hé" },
  { term: "反覆", pinyin: "fǎn fù" },
  { term: "終於", pinyin: "zhōng yú" },
  { term: "揭開", pinyin: "jiē kāi" },
  { term: "超聲波", pinyin: "chāo shēng bō" },
  { term: "障礙物", pinyin: "zhàng ài wù" },
  { term: "反射", pinyin: "fǎn shè" },
  { term: "雷達", pinyin: "léi dá" },
  { term: "類似", pinyin: "lèi sì" },
  { term: "顯示", pinyin: "xiǎn shì" },
  { term: "熒光屏", pinyin: "yíng guāng píng" },
  { term: "駕駛員", pinyin: "jià shǐ yuán" },
  { term: "張擇端", pinyin: "zhāng zé duān" },
  { term: "名揚中外", pinyin: "míng yáng zhōng wài" },
  { term: "汴梁", pinyin: "biàn liáng" },
  { term: "場面", pinyin: "chǎng miàn" },
  { term: "保存", pinyin: "bǎo cún" },
  { term: "故宮博物院", pinyin: "gù gōng bó wù yuàn" },
  { term: "撐船", pinyin: "chēng chuán" },
  { term: "攤販", pinyin: "tān fàn" },
  { term: "官吏", pinyin: "guān lì" },
  { term: "三百六十行", pinyin: "sān bǎi liù shí háng" },
  { term: "街市", pinyin: "jiē shì" },
  { term: "形態各異", pinyin: "xíng tài gè yì" },
  { term: "毛驢", pinyin: "máo lǘ" },
  { term: "悠閒", pinyin: "yōu xián" },
  { term: "一寸", pinyin: "yī cùn" },
  { term: "情景", pinyin: "qíng jǐng" },
  { term: "緊急", pinyin: "jǐn jí" },
  { term: "拽住", pinyin: "zhuài zhù" },
  { term: "命名", pinyin: "mìng míng" },
  { term: "上市", pinyin: "shàng shì" },
  { term: "名譽", pinyin: "míng yù" },
  { term: "股份", pinyin: "gǔ fèn" },
  { term: "市值", pinyin: "shì zhí" },
  { term: "計算", pinyin: "jì suàn" },
  { term: "過億", pinyin: "guò yì" },
  { term: "首富", pinyin: "shǒu fù" },
  { term: "身邊", pinyin: "shēn biān" },
  { term: "工��人員", pinyin: "gōng zuò rén yuán" },
  { term: "這位", pinyin: "zhè wèi" },
  { term: "富翁", pinyin: "fù wēng" },
  { term: "聯繫", pinyin: "lián xì" },
  { term: "議論", pinyin: "yì lùn" },
  { term: "軟塌塌", pinyin: "ruǎn tā tā" },
  { term: "襯衣", pinyin: "chèn yī" },
  { term: "坦言", pinyin: "tǎn yán" },
  { term: "工資", pinyin: "gōng zī" },
  { term: "很滿足", pinyin: "hěn mǎn zú" },
  { term: "認為", pinyin: "rèn wéi" },
  { term: "享受", pinyin: "xiǎng shòu" },
  { term: "搞科研", pinyin: "gǎo kē yán" },
  { term: "淡泊名利", pinyin: "dàn bó míng lì" },
  { term: "人民", pinyin: "rén mín" },
  { term: "攙扶", pinyin: "chān fú" },
  { term: "套鞋", pinyin: "tào xié" },
  { term: "一蹬", pinyin: "yī dēng" },
  { term: "年齡", pinyin: "nián líng" },
  { term: "心態", pinyin: "xīn tài" },
  { term: "肌肉彈性", pinyin: "jī ròu tán xìng" },
  { term: "業餘生活", pinyin: "yè yú shēng huó" },
  { term: "頤和園", pinyin: "yí hé yuán" },
  { term: "繞過", pinyin: "rào guò" },
  { term: "大殿", pinyin: "dà diàn" },
  { term: "綠漆", pinyin: "lǜ qī" },
  { term: "欄杆", pinyin: "lán gān" },
  { term: "橫檻", pinyin: "héng jiàn" },
  { term: "花草", pinyin: "huā cǎo" },
  { term: "栽滿", pinyin: "zāi mǎn" },
  { term: "微風", pinyin: "wēi fēng" },
  { term: "昆明湖", pinyin: "kūn míng hú" },
  { term: "神清氣爽", pinyin: "shén qīng qì shuǎng" },
  { term: "萬壽山", pinyin: "wàn shòu shān" },
  { term: "腳下", pinyin: "jiǎo xià" },
  { term: "八角寶塔形", pinyin: "bā jiǎo bǎo tǎ xíng" },
  { term: "建築", pinyin: "jiàn zhù" },
  { term: "聳立", pinyin: "sǒng lì" },
  { term: "琉璃瓦", pinyin: "liú lí wǎ" },
  { term: "閃閃發光", pinyin: "shǎn shǎn fā guāng" },
  { term: "佛香閣", pinyin: "fó xiāng gé" },
  { term: "排雲殿", pinyin: "pái yún diàn" },
  { term: "景色", pinyin: "jǐng sè" },
  { term: "蔥鬱", pinyin: "cōng yù" },
  { term: "樹叢", pinyin: "shù cóng" },
  { term: "掩映", pinyin: "yǎn yìng" },
  { term: "宮牆", pinyin: "gōng qiáng" },
  { term: "畫舫", pinyin: "huà fǎng" },
  { term: "幾乎", pinyin: "jī hū" },
  { term: "遠眺", pinyin: "yuǎn tiào" },
  { term: "白塔", pinyin: "bái tǎ" },
  { term: "堤岸", pinyin: "dī àn" },
  { term: "式樣", pinyin: "shì yàng" },
  { term: "垂柳", pinyin: "chuí liǔ" },
  { term: "自從", pinyin: "zì cóng" },
  { term: "認字", pinyin: "rèn zì" },
  { term: "倒不是", pinyin: "dào bù shì" },
  { term: "商務印書館", pinyin: "shāng wù yìn shū guǎn" },
  { term: "教科書", pinyin: "jiào kē shū" },
  { term: "第一冊", pinyin: "dì yī cè" },
  { term: "話說", pinyin: "huà shuō" },
  { term: "大勢", pinyin: "dà shì" },
  { term: "三國演義", pinyin: "sān guó yǎn yì" },
  { term: "舅父", pinyin: "jiù fù" },
  { term: "晚飯", pinyin: "wǎn fàn" },
  { term: "津津有味", pinyin: "jīn jīn yǒu wèi" },
  { term: "鐘頭", pinyin: "zhōng tóu" },
  { term: "懸念", pinyin: "xuán niàn" },
  { term: "催促", pinyin: "cuī cù" },
  { term: "豈", pinyin: "qǐ" },
  { term: "諸", pinyin: "zhū" },
  { term: "丟下", pinyin: "diū xià" },
  { term: "結局", pinyin: "jié jú" },
  { term: "聊齋志異", pinyin: "liáo zhāi zhì yì" },
  { term: "隨時", pinyin: "suí shí" },
  { term: "對於", pinyin: "duì yú" },
  { term: "徐霞客", pinyin: "xú xiá kè" },
  { term: "明朝末年", pinyin: "míng cháo mò nián" },
  { term: "走遍", pinyin: "zǒu biàn" },
  { term: "名山大川", pinyin: "míng shān dà chuān" },
  { term: "觀察", pinyin: "guān chá" },
  { term: "追求", pinyin: "zhuī qiú" },
  { term: "科舉功名", pinyin: "kē jǔ gōng míng" },
  { term: "埋頭", pinyin: "mái tóu" },
  { term: "古今史籍", pinyin: "gǔ jīn shǐ jí" },
  { term: "山海圖經", pinyin: "shān hǎi tú jīng" },
  { term: "收集", pinyin: "shōu jí" },
  { term: "研讀", pinyin: "yán dú" },
  { term: "簡略", pinyin: "jiǎn lüè" },
  { term: "相互矛盾", pinyin: "xiāng hù máo dùn" },
  { term: "雄心壯志", pinyin: "xióng xīn zhuàng zhì" },
  { term: "考察", pinyin: "kǎo chá" },
  { term: "大量", pinyin: "dà liàng" },
  { term: "攀險峰", pinyin: "pān xiǎn fēng" },
  { term: "涉危澗", pinyin: "shè wēi jiàn" },
  { term: "疲勞", pinyin: "pí láo" },
  { term: "當日見聞", pinyin: "dàng rì jiàn wén" },
  { term: "荒野露宿", pinyin: "huāng yě lù sù" },
  { term: "棲身洞穴", pinyin: "qī shēn dòng xué" },
  { term: "燃松拾穗", pinyin: "rán sōng shí suì" },
  { term: "走筆為記", pinyin: "zǒu bǐ wéi jì" },
  { term: "治安", pinyin: "zhì ān" },
  { term: "盜匪橫行", pinyin: "dào fěi héng xíng" },
  { term: "艱苦", pinyin: "jiān kǔ" },
  { term: "難耐", pinyin: "nán nài" },
  { term: "旅途勞頓", pinyin: "lǚ tú láo dùn" },
  { term: "衡陽", pinyin: "héng yáng" },
  { term: "遭遇", pinyin: "zāo yù" },
  { term: "土匪", pinyin: "tǔ fěi" },
  { term: "造紙術", pinyin: "zào zhǐ shù" },
  { term: "偉大", pinyin: "wěi dà" },
  { term: "貢獻", pinyin: "gòng xiàn" },
  { term: "祖先", pinyin: "zǔ xiān" },
  { term: "創造", pinyin: "chuàng zào" },
  { term: "記錄", pinyin: "jì lù" },
  { term: "刻", pinyin: "kè" },
  { term: "龜甲", pinyin: "guī jiǎ" },
  { term: "獸骨", pinyin: "shòu gǔ" },
  { term: "鑄刻", pinyin: "zhù kè" },
  { term: "竹片", pinyin: "zhú piàn" },
  { term: "攜帶", pinyin: "xié dài" },
  { term: "學富五車", pinyin: "xué fù wǔ chē" },
  { term: "蠶絲", pinyin: "cán sī" },
  { term: "帛", pinyin: "bó" },
  { term: "普及", pinyin: "pǔ jí" },
  { term: "蠶繭", pinyin: "cán jiǎn" },
  { term: "製作", pinyin: "zhì zuò" },
  { term: "盛放", pinyin: "chéng fàng" },
  { term: "篾席", pinyin: "miè xí" },
  { term: "薄片", pinyin: "báo piàn" },
  { term: "粗糙", pinyin: "cū cāo" },
  { term: "蔡倫", pinyin: "Cài Lún" },
  { term: "積累", pinyin: "jī lěi" },
  { term: "麻頭", pinyin: "má tóu" },
  { term: "稻草", pinyin: "dào cǎo" },
  { term: "破布", pinyin: "pò bù" },
  { term: "搗爛成漿", pinyin: "dǎo làn chéng jiāng" },
  { term: "滿足", pinyin: "mǎn zú" },
  { term: "需要", pinyin: "xū yào" },
  { term: "東南方", pinyin: "dōng nán fāng" },
  { term: "海峽", pinyin: "hǎi xiá" },
  { term: "沿海", pinyin: "yán hǎi" },
  { term: "隱隱約約", pinyin: "yǐn yǐn yuē yuē" },
  { term: "雲朵", pinyin: "yún duǒ" },
  { term: "形狀狹長", pinyin: "xíng zhuàng xiá cháng" },
  { term: "紡織", pinyin: "fǎng zhī" },
  { term: "縱貫南北", pinyin: "zòng guàn nán běi" },
  { term: "海拔", pinyin: "hǎi bá" },
  { term: "東部", pinyin: "dōng bù" },
  { term: "緞帶", pinyin: "duàn dài" },
  { term: "瀑布", pinyin: "pù bù" },
  { term: "湖泊", pinyin: "hú pō" },
  { term: "四季常青", pinyin: "sì jì cháng qīng" },
  { term: "西南部", pinyin: "xī nán bù" },
  { term: "市郊", pinyin: "shì jiāo" },
  { term: "大屯山風景區", pinyin: "dà tún shān fēng jǐng qū" },
  { term: "聞名世界", pinyin: "wén míng shì jiè" },
  { term: "游覽勝地", pinyin: "yóu lǎn shèng dì" },
  { term: "調劑", pinyin: "tiáo jì" },
  { term: "水稻", pinyin: "shuǐ dào" },
  { term: "優越", pinyin: "yōu yuè" },
  { term: "樟腦", pinyin: "zhāng nǎo" },
  { term: "魚蝦", pinyin: "yú xiā" },
  { term: "品種", pinyin: "pǐn zhǒng" },
  { term: "稀有", pinyin: "xī yǒu" },
  { term: "珍貴", pinyin: "zhēn guì" },
  { term: "鳥語花香", pinyin: "niǎo yǔ huā xiāng" },
  { term: "尊敬", pinyin: "zūn jìng" },
  { term: "感情", pinyin: "gǎn qíng" },
  { term: "印象", pinyin: "yìn xiàng" },
  { term: "田壟", pinyin: "tián lǒng" },
  { term: "郊遊", pinyin: "jiāo yóu" },
  { term: "領頭", pinyin: "lǐng tóu" },
  { term: "狹窄", pinyin: "xiá zhǎi" },
  { term: "阡陌", pinyin: "qiān mò" },
  { term: "耕牛", pinyin: "gēng niú" },
  { term: "讓路", pinyin: "ràng lù" },
  { term: "鞋襪", pinyin: "xié wà" },
  { term: "踟躕", pinyin: "chí chú" },
  { term: "遲疑", pinyin: "chí yí" },
  { term: "呆", pinyin: "dāi" },
  { term: "深褐色", pinyin: "shēn hè sè" },
  { term: "消失", pinyin: "xiāo shī" },
  { term: "恩惠", pinyin: "ēn huì" },
  { term: "沉默", pinyin: "chén mò" },
  { term: "犁", pinyin: "lí" },
  { term: "鬆土", pinyin: "sōng tǔ" },
  { term: "下種", pinyin: "xià zhǒng" },
  { term: "農閒", pinyin: "nóng xián" },
  { term: "擔當", pinyin: "dān dāng" },
  { term: "搬運", pinyin: "bān yùn" },
  { term: "繞", pinyin: "rào" },
  { term: "石磨", pinyin: "shí mò" },
  { term: "不計程", pinyin: "bù jì chéng" },
  { term: "也許", pinyin: "yě xǔ" },
  { term: "嫩草", pinyin: "nèn cǎo" },
  { term: "閒適", pinyin: "xián shì" },
  { term: "成群奔跑", pinyin: "chéng qún bēn pǎo" },
  { term: "石拱橋", pinyin: "shí gǒng qiáo" },
  { term: "弧形", pinyin: "hú xíng" },
  { term: "臥虹", pinyin: "wò hóng" },
  { term: "飛虹", pinyin: "fēi hóng" },
  { term: "形容", pinyin: "xíng róng" },
  { term: "長虹臥波", pinyin: "cháng hóng wò bō" },
  { term: "悠久", pinyin: "yōu jiǔ" },
  { term: "旅人橋", pinyin: "lǚ rén qiáo" },
  { term: "建成", pinyin: "jiàn chéng" },
  { term: "杰作", pinyin: "jié zuò" },
  { term: "趙縣", pinyin: "zhào xiàn" },
  { term: "雄偉", pinyin: "xióng wěi" },
  { term: "合乎", pinyin: "hé hū" },
  { term: "巧妙絕倫", pinyin: "qiǎo miào jué lún" },
  { term: "一張弓", pinyin: "yī zhāng gōng" },
  { term: "陡坡", pinyin: "dǒu pō" },
  { term: "兩肩", pinyin: "liǎng jiān" },
  { term: "節約", pinyin: "jié yuē" },
  { term: "重量", pinyin: "zhòng liàng" },
  { term: "暴漲", pinyin: "bào zhǎng" },
  { term: "衝擊", pinyin: "chōng jī" },
  { term: "拱圈", pinyin: "gǒng quān" },
  { term: "形狀", pinyin: "xíng zhuàng" },
  { term: "合攏", pinyin: "hé lǒng" },
  { term: "獨立", pinyin: "dú lì" },
  { term: "支撐", pinyin: "zhī chēng" },
  { term: "能否", pinyin: "néng fǒu" },
  { term: "事實", pinyin: "shì shí" },
  { term: "杭州", pinyin: "háng zhōu" },
  { term: "西湖", pinyin: "xī hú" },
  { term: "嫩柳", pinyin: "nèn liǔ" },
  { term: "翠竹", pinyin: "cuì zhú" },
  { term: "生活", pinyin: "shēng huó" },
  { term: "圖畫", pinyin: "tú huà" },
  { term: "拴住", pinyin: "shuān zhù" },
  { term: "失望", pinyin: "shī wàng" },
  { term: "目之所及", pinyin: "mù zhī suǒ jí" },
  { term: "綠色", pinyin: "lǜ sè" },
  { term: "滌清", pinyin: "dí qīng" },
  { term: "萬慮", pinyin: "wàn lǜ" },
  { term: "不冷不熱", pinyin: "bù lěng bù rè" },
  { term: "若干種", pinyin: "ruò gān zhǒng" },
  { term: "一項", pinyin: "yī xiàng" },
  { term: "滿意", pinyin: "mǎn yì" },
  { term: "成都", pinyin: "chéng dū" },
  { term: "或者", pinyin: "huò zhě" },
  { term: "合適", pinyin: "hé shì" },
  { term: "和暖", pinyin: "hé nuǎn" },
  { term: "寒冷", pinyin: "hán lěng" },
  { term: "著名", pinyin: "zhù míng" },
  { term: "天壇", pinyin: "tiān tán" },
  { term: "東側", pinyin: "dōng cè" },
  { term: "佔地面積", pinyin: "zhàn dì miàn jī" },
  { term: "建築區域", pinyin: "jiàn zhù qū yù" },
  { term: "訓練館", pinyin: "xùn liàn guǎn" },
  { term: "揮汗如雨", pinyin: "huī hàn rú yǔ" },
  { term: "完畢", pinyin: "wán bì" },
  { term: "跟隨", pinyin: "gēn suí" },
  { term: "熱身", pinyin: "rè shēn" },
  { term: "各式用品", pinyin: "gè shì yòng pǐn" },
  { term: "外行人", pinyin: "wài háng rén" },
  { term: "鮮艷", pinyin: "xiān yàn" },
  { term: "頑強拼搏", pinyin: "wán qiáng pīn bó" },
  { term: "橫幅", pinyin: "héng fú" },
  { term: "榮耀", pinyin: "róng yào" },
  { term: "輝煌", pinyin: "huī huáng" },
  { term: "墊球跑", pinyin: "diàn qiú pǎo" },
  { term: "雜技", pinyin: "zá jì" },
  { term: "熟練掌握", pinyin: "shú liàn zhǎng wò" },
  { term: "問及", pinyin: "wèn jí" },
  { term: "世紀", pinyin: "shì jì" },
  { term: "汽車", pinyin: "qì chē" },
  { term: "新加坡", pinyin: "xīn jiā pō" },
  { term: "知名人士", pinyin: "zhī míng rén shì" },
  { term: "冷氣機", pinyin: "lěng qì jī" },
  { term: "解釋", pinyin: "jiě shì" },
  { term: "熱帶", pinyin: "rè dài" },
  { term: "東南亞", pinyin: "dōng nán yà" },
  { term: "生產力", pinyin: "shēng chǎn lì" },
  { term: "生活水準", pinyin: "shēng huó shuǐ zhǔn" },
  { term: "實事求是", pinyin: "shí shì qiú shì" },
  { term: "上述", pinyin: "shàng shù" },
  { term: "報道", pinyin: "bào dào" },
  { term: "突發奇想", pinyin: "tū fā qí xiǎng" },
  { term: "記者", pinyin: "jì zhě" },
  { term: "糟糕", pinyin: "zāo gāo" },
  { term: "中旬", pinyin: "zhōng xún" },
  { term: "報紙", pinyin: "bào zhǐ" },
  { term: "人類", pinyin: "rén lèi" },
  { term: "獲此“殊榮”", pinyin: "huò cǐ “shū róng”" },
  { term: "塑膠袋", pinyin: "sù liào dài" },
  { term: "家族", pinyin: "jiā zú" },
  { term: "包括", pinyin: "bāo kuò" },
  { term: "酸奶杯", pinyin: "suān nǎi bēi" },
  { term: "雪糕杯", pinyin: "xuě gāo bēi" },
  { term: "廢棄物", pinyin: "fèi qì wù" },
  { term: "體積大", pinyin: "tǐ jī dà" },
  { term: "不降解", pinyin: "bù jiàng jiě" },
  { term: "社會問題", pinyin: "shè huì wèn tí" },
  { term: "比如", pinyin: "bǐ rú" },
  { term: "散落", pinyin: "sàn luò" },
  { term: "牲畜", pinyin: "shēng chù" },
  { term: "吞食", pinyin: "tūn shí" },
  { term: "造成", pinyin: "zào chéng" },
  { term: "焚燒處理", pinyin: "fén shāo chǔ lǐ" },
  { term: "化學", pinyin: "huà xué" },
  { term: "化合物", pinyin: "huà hé wù" },
  { term: "卓爾不群", pinyin: "zhuó ěr bù qún" },
  { term: "因而", pinyin: "yīn ér" },
  { term: "淡而光潤", pinyin: "dàn ér guāng rùn" },
  { term: "耳熟能詳", pinyin: "ěr shú néng xiáng" },
  { term: "偶爾一瞥", pinyin: "ǒu ěr yī piē" },
  { term: "二噁英", pinyin: "èr è yīng" },
  { term: "周而復始", pinyin: "zhōu ér fù shǐ" },
  { term: "呼嘯而過", pinyin: "hū xiào ér guò" },
  { term: "然而", pinyin: "rán ér" },
  { term: "不辭而別", pinyin: "bù cí ér bié" },
];

window.SPECIAL_WORDS = [
  { term: "規矩", pinyin: "guī ju", audioMode: "recording" },
  { term: "時候", pinyin: "shí hou", audioMode: "recording" },
  { term: "餃子", pinyin: "jiǎo zi", audioMode: "recording" },
  { term: "忍不住", pinyin: "rěn ·bù zhù", audioMode: "recording" },
  { term: "榛子", pinyin: "zhēn zi", audioMode: "recording" },
  { term: "摻和", pinyin: "chān huo", audioMode: "recording" },
  { term: "零七八碎兒", pinyin: "líng qī bā suìr", audioMode: "recording" },
  { term: "玩意兒", pinyin: "wán yìr", audioMode: "recording" },
  { term: "風箏", pinyin: "fēng zheng", audioMode: "recording" },
  { term: "擦黑兒", pinyin: "cā hēir", audioMode: "recording" },
  { term: "嫩嫩的", pinyin: "nèn nèn de", audioMode: "recording" },
  { term: "青草味兒", pinyin: "qīng cǎo wèir", audioMode: "recording" },
  { term: "樹葉兒", pinyin: "shù yèr", audioMode: "recording" },
  { term: "小草兒", pinyin: "xiǎo cǎor", audioMode: "recording" },
  { term: "告訴", pinyin: "gào su", audioMode: "recording" },
  { term: "簌簌地", pinyin: "sù sù de", audioMode: "recording" },
  { term: "種穀子", pinyin: "zhòng gǔ zi", audioMode: "recording" },
  { term: "來不及", pinyin: "lái ·bù jí", audioMode: "recording" },
  { term: "石子兒", pinyin: "shí zǐr", audioMode: "recording" },
  { term: "石塊兒", pinyin: "shí kuàir", audioMode: "recording" },
  { term: "歡快活潑", pinyin: "huān kuài huó po", audioMode: "recording" },
  { term: "踮着腳", pinyin: "diǎn zhe jiǎo", audioMode: "recording" },
  { term: "一會兒", pinyin: "yī huìr", audioMode: "recording" },
  { term: "園子裏", pinyin: "yuán zi ·lǐ", audioMode: "recording" },
  { term: "一個勁兒", pinyin: "yī gè jìnr", audioMode: "recording" },
  { term: "菱角", pinyin: "líng jiao", audioMode: "recording" },
  { term: "葡萄", pinyin: "pú ·táo", audioMode: "recording" },
  { term: "奶奶", pinyin: "nǎi nai", audioMode: "recording" },
  { term: "差不多", pinyin: "chà ·bù duō", audioMode: "recording" },
  { term: "护士", pinyin: "hù shi", audioMode: "recording" },
  { term: "地理知識", pinyin: "dì lǐ zhī shi", audioMode: "recording" },
  { term: "大部分", pinyin: "dà bù fen", audioMode: "recording" },
  { term: "先生", pinyin: "xiān sheng", audioMode: "recording" },
  { term: "意思", pinyin: "yì si", audioMode: "recording" },
  { term: "認識", pinyin: "rèn shi", audioMode: "recording" },
  { term: "喜歡", pinyin: "xǐ huan", audioMode: "recording" },
  { term: "襯着", pinyin: "chèn zhe", audioMode: "recording" },
  { term: "芍藥", pinyin: "sháo yao", audioMode: "recording" },
  { term: "泊了片刻", pinyin: "bó le piàn kè", audioMode: "recording" },
  { term: "眼睛", pinyin: "yǎn jing", audioMode: "recording" },
  { term: "撥着船", pinyin: "bō zhe chuán", audioMode: "recording" },
  { term: "早晨", pinyin: "zǎo chen", audioMode: "recording" },
  { term: "鈴鐺", pinyin: "líng dang", audioMode: "recording" },
  { term: "屋子", pinyin: "wū zi", audioMode: "recording" },
  { term: "蒼蠅", pinyin: "cāng ying", audioMode: "recording" },
  { term: "耳朵", pinyin: "ěr duo", audioMode: "recording" },
  { term: "熱鬧", pinyin: "rè nao", audioMode: "recording" },
  { term: "功夫", pinyin: "gōng fu", audioMode: "recording" },
  { term: "買賣", pinyin: "mǎi mai", audioMode: "recording" },
  { term: "生意人", pinyin: "shēng yi rén", audioMode: "recording" },
  { term: "招牌", pinyin: "zhāo pai", audioMode: "recording" },
  { term: "作坊", pinyin: "zuō fang", audioMode: "recording" },
  { term: "挑着擔", pinyin: "tiāo zhe dàn", audioMode: "recording" },
  { term: "溜達", pinyin: "liū da", audioMode: "recording" },
  { term: "橋北頭", pinyin: "qiáo běi tou", audioMode: "recording" },
  { term: "一乘轎子", pinyin: "yī shèng jiào zi", audioMode: "recording" },
  { term: "馬籠頭", pinyin: "mǎ lóng tou", audioMode: "recording" },
  { term: "名字", pinyin: "míng zi", audioMode: "recording" },
  { term: "學生", pinyin: "xué sheng", audioMode: "recording" },
  { term: "衣服", pinyin: "yī fu", audioMode: "recording" },
  { term: "踏實做人", pinyin: "tà shi zuò rén", audioMode: "recording" },
  { term: "硬朗", pinyin: "yìng lang", audioMode: "recording" },
  { term: "數不清", pinyin: "shǔ ·bù qīng", audioMode: "recording" },
  { term: "針線笸籮", pinyin: "zhēn xiàn pǒ luo", audioMode: "recording" },
  { term: "學問", pinyin: "xué wen", audioMode: "recording" },
  { term: "撈出來", pinyin: "lāo chū ·lái", audioMode: "recording" },
  { term: "便宜", pinyin: "pián yi", audioMode: "recording" },
  { term: "梭子", pinyin: "suō zi", audioMode: "recording" },
  { term: "脊梁", pinyin: "jǐ ·liáng", audioMode: "recording" },
  { term: "甘蔗", pinyin: "gān zhe", audioMode: "recording" },
  { term: "容不下", pinyin: "róng ·bù xià", audioMode: "recording" },
  { term: "鬥不過", pinyin: "dòu ·bù guò", audioMode: "recording" },
  { term: "畜牲", pinyin: "chù sheng", audioMode: "recording" },
  { term: "收成", pinyin: "shōu cheng", audioMode: "recording" },
  { term: "搖搖尾巴", pinyin: "yáo yao wěi ba", audioMode: "recording" },
  { term: "擺擺耳朵", pinyin: "bǎi bai ěr duo", audioMode: "recording" },
  { term: "地方", pinyin: "dì fang", audioMode: "recording" },
];

window.FREQ_WORDS = [
  { term: "子", pinyin: "zǐ" },
  { term: "人", pinyin: "rén" },
  { term: "心", pinyin: "xīn" },
  { term: "不", pinyin: "bù、bú", note: "多音字" },
  { term: "大", pinyin: "dà、dài", note: "多音字" },
  { term: "地", pinyin: "dì、de", note: "多音字" },
  { term: "動", pinyin: "dòng" },
  { term: "氣", pinyin: "qì" },
  { term: "頭", pinyin: "tóu、tou", note: "多音字" },
  { term: "生", pinyin: "shēng" },
  { term: "發/髮", pinyin: "發：fā、fà；髮：fà", note: "多音字" },
  { term: "力", pinyin: "lì" },
  { term: "出/齣", pinyin: "出：chū；齣：chū", note: "多音字" },
  { term: "行", pinyin: "xíng、háng", note: "多音字" },
  { term: "水", pinyin: "shuǐ" },
  { term: "體", pinyin: "tǐ、tī", note: "多音字" },
  { term: "事", pinyin: "shì" },
  { term: "一", pinyin: "yī、yí、yì", note: "多音字" },
  { term: "意", pinyin: "yì" },
  { term: "手", pinyin: "shǒu" },
  { term: "面/麵", pinyin: "面：miàn；麵：miàn", note: "多音字" },
  { term: "風", pinyin: "fēng" },
  { term: "天", pinyin: "tiān" },
  { term: "法", pinyin: "fǎ" },
  { term: "外", pinyin: "wài" },
  { term: "電", pinyin: "diàn" },
  { term: "流", pinyin: "liú" },
  { term: "工", pinyin: "gōng" },
  { term: "情", pinyin: "qíng" },
  { term: "重", pinyin: "zhòng、chóng", note: "多音字" },
  { term: "自", pinyin: "zì" },
  { term: "然", pinyin: "rán" },
  { term: "無", pinyin: "wú" },
  { term: "學", pinyin: "xué" },
  { term: "上", pinyin: "shàng、shǎng", note: "多音字" },
  { term: "定", pinyin: "dìng" },
  { term: "化", pinyin: "huà" },
  { term: "分", pinyin: "fēn、fèn", note: "多音字" },
  { term: "家/傢", pinyin: "家：jiā、jia；傢：jiā", note: "多音字" },
  { term: "開", pinyin: "kāi" },
  { term: "公", pinyin: "gōng" },
  { term: "機", pinyin: "jī" },
  { term: "口", pinyin: "kǒu" },
  { term: "理", pinyin: "lǐ" },
  { term: "高", pinyin: "gāo" },
  { term: "名", pinyin: "míng" },
  { term: "實", pinyin: "shí" },
  { term: "用", pinyin: "yòng" },
  { term: "長", pinyin: "cháng、zhǎng", note: "多音字" },
  { term: "成", pinyin: "chéng" },
  { term: "光", pinyin: "guāng" },
  { term: "會", pinyin: "huì、kuài", note: "多音字" },
  { term: "文", pinyin: "wén" },
  { term: "性", pinyin: "xìng" },
  { term: "火", pinyin: "huǒ" },
  { term: "點", pinyin: "diǎn" },
  { term: "國", pinyin: "guó" },
  { term: "下", pinyin: "xià" },
  { term: "道", pinyin: "dào" },
  { term: "合/閤", pinyin: "合：hé、gě；閤：gé", note: "多音字" },
  { term: "花", pinyin: "huā" },
  { term: "年", pinyin: "nián" },
  { term: "主", pinyin: "zhǔ" },
  { term: "制/製", pinyin: "制：zhì；製：zhì", note: "多音字" },
  { term: "身", pinyin: "shēn" },
  { term: "時", pinyin: "shí" },
  { term: "物", pinyin: "wù" },
  { term: "小", pinyin: "xiǎo" },
  { term: "中", pinyin: "zhōng、zhòng", note: "多音字" },
  { term: "場", pinyin: "chǎng、cháng", note: "多音字" },
  { term: "后/後", pinyin: "后：hòu；後：hòu", note: "多音字" },
  { term: "作", pinyin: "zuò、zuō", note: "多音字" },
  { term: "相", pinyin: "xiāng、xiàng", note: "多音字" },
  { term: "度", pinyin: "dù、duó", note: "多音字" },
  { term: "海", pinyin: "hǎi" },
  { term: "同", pinyin: "tóng" },
  { term: "當/噹", pinyin: "當：dāng、dàng；噹：dāng", note: "多音字" },
  { term: "民", pinyin: "mín" },
  { term: "線", pinyin: "xiàn" },
  { term: "有", pinyin: "yǒu、yòu", note: "多音字" },
  { term: "方", pinyin: "fāng" },
  { term: "前", pinyin: "qián" },
  { term: "山", pinyin: "shān" },
  { term: "聲", pinyin: "shēng" },
  { term: "本", pinyin: "běn" },
  { term: "得", pinyin: "dé、děi、de", note: "多音字" },
  { term: "放", pinyin: "fàng" },
  { term: "通", pinyin: "tōng" },
  { term: "戰", pinyin: "zhàn" },
  { term: "報", pinyin: "bào" },
  { term: "對", pinyin: "duì" },
  { term: "交", pinyin: "jiāo" },
  { term: "教", pinyin: "jiào、jiāo", note: "多音字" },
  { term: "門", pinyin: "mén" },
  { term: "回/迴", pinyin: "回：huí；迴：huí", note: "多音字" },
  { term: "進", pinyin: "jìn" },
  { term: "來", pinyin: "lái" },
  { term: "量", pinyin: "liáng、liàng", note: "多音字" },
  { term: "路", pinyin: "lù" },
  { term: "明", pinyin: "míng" },
  { term: "平", pinyin: "píng" },
  { term: "熱", pinyin: "rè" },
  { term: "日", pinyin: "rì" },
  { term: "色", pinyin: "sè" },
  { term: "失", pinyin: "shī" },
  { term: "正", pinyin: "zhèng、zhēng", note: "多音字" },
  { term: "轉", pinyin: "zhuǎn、zhuàn", note: "多音字" },
  { term: "信", pinyin: "xìn" },
  { term: "業", pinyin: "yè" },
  { term: "車", pinyin: "chē、jū", note: "多音字" },
  { term: "見", pinyin: "jiàn、xiàn", note: "多音字" },
  { term: "空", pinyin: "kōng、kòng", note: "多音字" },
  { term: "落", pinyin: "luò、lào、là", note: "多音字" },
  { term: "難", pinyin: "nán、nàn", note: "多音字" },
  { term: "起", pinyin: "qǐ" },
  { term: "眼", pinyin: "yǎn" },
  { term: "打", pinyin: "dǎ" },
  { term: "過", pinyin: "guò、guō", note: "多音字" },
  { term: "軍", pinyin: "jūn" },
  { term: "期", pinyin: "qī、jī", note: "多音字" },
  { term: "取", pinyin: "qǔ" },
  { term: "調", pinyin: "diào、tiáo", note: "多音字" },
  { term: "白", pinyin: "bái" },
  { term: "產", pinyin: "chǎn" },
  { term: "解", pinyin: "jiě、jiè、xiè", note: "多音字" },
  { term: "收", pinyin: "shōu" },
  { term: "書", pinyin: "shū" },
  { term: "立", pinyin: "lì" },
  { term: "神", pinyin: "shén" },
  { term: "音", pinyin: "yīn" },
  { term: "好", pinyin: "hǎo、hào", note: "多音字" },
  { term: "結", pinyin: "jié、jiē", note: "多音字" },
  { term: "變", pinyin: "biàn" },
  { term: "利", pinyin: "lì" },
  { term: "求", pinyin: "qiú" },
  { term: "語", pinyin: "yǔ、yù", note: "多音字" },
  { term: "病", pinyin: "bìng" },
  { term: "精", pinyin: "jīng" },
  { term: "老", pinyin: "lǎo" },
  { term: "視", pinyin: "shì" },
  { term: "數", pinyin: "shù、shǔ、shuò", note: "多音字" },
  { term: "新", pinyin: "xīn" },
  { term: "原", pinyin: "yuán" },
  { term: "反", pinyin: "fǎn" },
  { term: "感", pinyin: "gǎn" },
  { term: "可", pinyin: "kě、kè", note: "多音字" },
  { term: "目", pinyin: "mù" },
  { term: "品", pinyin: "pǐn" },
  { term: "傳", pinyin: "chuán、zhuàn", note: "多音字" },
  { term: "接", pinyin: "jiē" },
  { term: "親", pinyin: "qīn、qìng", note: "多音字" },
  { term: "言", pinyin: "yán" },
  { term: "于/於", pinyin: "yú" },
  { term: "安", pinyin: "ān" },
  { term: "導", pinyin: "dǎo" },
  { term: "複/復", pinyin: "複：fù；復：fù", note: "多音字" },
  { term: "能", pinyin: "néng" },
  { term: "強", pinyin: "qiáng、qiǎng、jiàng", note: "多音字" },
  { term: "務", pinyin: "wù" },
  { term: "要", pinyin: "yào、yāo", note: "多音字" },
  { term: "邊", pinyin: "biān" },
  { term: "集", pinyin: "jí" },
  { term: "金", pinyin: "jīn" },
  { term: "經", pinyin: "jīng、jìng", note: "多音字" },
  { term: "樂", pinyin: "lè、yuè、yào", note: "多音字" },
  { term: "論", pinyin: "lùn、lún", note: "多音字" },
  { term: "美", pinyin: "měi" },
  { term: "入", pinyin: "rù" },
  { term: "領", pinyin: "lǐng" },
  { term: "權", pinyin: "quán" },
  { term: "任", pinyin: "rèn、rén", note: "多音字" },
  { term: "勢", pinyin: "shì" },
  { term: "受", pinyin: "shòu" },
  { term: "說", pinyin: "shuō、shuì、yuè", note: "多音字" },
  { term: "應", pinyin: "yīng、yìng", note: "多音字" },
  { term: "員", pinyin: "yuán、yún、yùn", note: "多音字" },
  { term: "政", pinyin: "zhèng" },
  { term: "保", pinyin: "bǎo" },
  { term: "程", pinyin: "chéng" },
  { term: "而", pinyin: "ér" },
  { term: "干/乾/幹", pinyin: "干：gān、gàn；乾：gān、qián；幹：gàn", note: "多音字" },
  { term: "關", pinyin: "guān" },
  { term: "畫", pinyin: "huà、huá", note: "多音字" },
  { term: "話", pinyin: "huà" },
  { term: "價/价", pinyin: "jià" },
  { term: "提", pinyin: "tí、dī", note: "多音字" },
  { term: "想", pinyin: "xiǎng" },
  { term: "���", pinyin: "xiàng" },
  { term: "血", pinyin: "xuè、xiě", note: "多音字" },
  { term: "愛", pinyin: "ài" },
  { term: "商", pinyin: "shāng" },
  { term: "深", pinyin: "shēn" },
  { term: "石", pinyin: "shí、dàn", note: "多音字" },
  { term: "食", pinyin: "shí、sì", note: "多音字" },
  { term: "世", pinyin: "shì" },
  { term: "現", pinyin: "xiàn" },
  { term: "形", pinyin: "xíng" },
  { term: "選", pinyin: "xuǎn" },
  { term: "養", pinyin: "yǎng" },
  { term: "以", pinyin: "yǐ" },
  { term: "運", pinyin: "yùn" },
  { term: "單", pinyin: "dān、chán、shàn", note: "多音字" },
  { term: "號", pinyin: "hào、háo", note: "多音字" },
  { term: "料", pinyin: "liào" },
  { term: "內", pinyin: "nèi" },
  { term: "容", pinyin: "róng" },
  { term: "圖", pinyin: "tú" },
  { term: "效", pinyin: "xiào" },
  { term: "義", pinyin: "yì" },
  { term: "標", pinyin: "biāo" },
  { term: "表/錶", pinyin: "biǎo" },
  { term: "查", pinyin: "chá、zhā", note: "多音字" },
  { term: "防", pinyin: "fáng" },
  { term: "功", pinyin: "gōng" },
  { term: "計", pinyin: "jì" },
  { term: "節", pinyin: "jié、jiē", note: "多音字" },
  { term: "客", pinyin: "kè" },
  { term: "苦", pinyin: "kǔ" },
  { term: "全", pinyin: "quán" },
  { term: "傷", pinyin: "shāng" },
  { term: "特", pinyin: "tè" },
  { term: "望", pinyin: "wàng" },
  { term: "先", pinyin: "xiān" },
  { term: "星", pinyin: "xīng" },
  { term: "造", pinyin: "zào" },
  { term: "裝", pinyin: "zhuāng" },
  { term: "別/彆", pinyin: "別：bié、biè；彆：biè", note: "多音字" },
  { term: "兵", pinyin: "bīng" },
  { term: "常", pinyin: "cháng" },
  { term: "處", pinyin: "chǔ、chù", note: "多音字" },
  { term: "代", pinyin: "dài" },
  { term: "帶", pinyin: "dài" },
  { term: "管", pinyin: "guǎn" },
  { term: "和", pinyin: "hé、hè、huó、huò、hú", note: "多音字" },
  { term: "紅", pinyin: "hóng、gōng", note: "多音字" },
  { term: "擊", pinyin: "jī" },
  { term: "急", pinyin: "jí" },
  { term: "居", pinyin: "jū、jù", note: "多音字" },
  { term: "命", pinyin: "mìng" },
  { term: "女", pinyin: "nǚ、rǔ", note: "多音字" },
  { term: "推", pinyin: "tuī" },
  { term: "位", pinyin: "wèi" },
  { term: "修", pinyin: "xiū" },
  { term: "游", pinyin: "yóu" },
  { term: "在", pinyin: "zài" },
  { term: "資", pinyin: "zī" },
  { term: "備", pinyin: "bèi" },
  { term: "步", pinyin: "bù" },
  { term: "存", pinyin: "cún" },
  { term: "房", pinyin: "fáng" },
  { term: "告", pinyin: "gào" },
  { term: "觀", pinyin: "guān、guàn", note: "多音字" },
  { term: "間", pinyin: "jiān、jiàn", note: "多音字" },
  { term: "劇", pinyin: "jù" },
  { term: "看", pinyin: "kàn、kān", note: "多音字" },
  { term: "連", pinyin: "lián" },
  { term: "切", pinyin: "qiē、qiè", note: "多音字" },
  { term: "如", pinyin: "rú" },
  { term: "散", pinyin: "sǎn、sàn", note: "多音字" },
  { term: "異", pinyin: "yì" },
  { term: "知", pinyin: "zhī" },
  { term: "案", pinyin: "àn" },
  { term: "草", pinyin: "cǎo" },
  { term: "飛", pinyin: "fēi" },
  { term: "改", pinyin: "gǎi" },
  { term: "冷", pinyin: "lěng" },
  { term: "皮", pinyin: "pí" },
  { term: "區", pinyin: "qū、ōu", note: "多音字" },
  { term: "使", pinyin: "shǐ" },
  { term: "士", pinyin: "shì" },
  { term: "守", pinyin: "shǒu" },
  { term: "算", pinyin: "suàn" },
  { term: "台/颱/枱", pinyin: "tái" },
  { term: "為", pinyin: "wèi、wéi", note: "多音字" },
  { term: "演", pinyin: "yǎn" },
  { term: "樣", pinyin: "yàng" },
  { term: "直", pinyin: "zhí" },
  { term: "職", pinyin: "zhí" },
  { term: "種", pinyin: "zhòng、zhǒng", note: "多音字" },
  { term: "專", pinyin: "zhuān" },
  { term: "辦", pinyin: "bàn" },
  { term: "除", pinyin: "chú" },
  { term: "從", pinyin: "cóng、zòng", note: "多音字" },
  { term: "低", pinyin: "dī" },
  { term: "斷", pinyin: "duàn" },
  { term: "隊", pinyin: "duì" },
  { term: "惡", pinyin: "è、wù、ě", note: "多音字" },
  { term: "果", pinyin: "guǒ" },
  { term: "近", pinyin: "jìn" },
  { term: "留", pinyin: "liú" },
  { term: "木", pinyin: "mù" },
  { term: "配", pinyin: "pèi" },
  { term: "片", pinyin: "piàn、piān", note: "多音字" },
  { term: "評", pinyin: "píng" },
  { term: "師", pinyin: "shī" },
  { term: "思", pinyin: "sī、sāi", note: "多音字" },
  { term: "消", pinyin: "xiāo" },
  { term: "笑", pinyin: "xiào" },
  { term: "真", pinyin: "zhēn" },
  { term: "比", pinyin: "bǐ" },
  { term: "波", pinyin: "bō" },
  { term: "稱", pinyin: "chēng、chèn、chèng", note: "多音字" },
  { term: "多", pinyin: "duō" },
  { term: "格", pinyin: "gé、gē", note: "多音字" },
  { term: "害", pinyin: "hài" },
  { term: "護", pinyin: "hù" },
  { term: "建", pinyin: "jiàn" },
  { term: "角", pinyin: "jiǎo、jué", note: "多音字" },
  { term: "驚", pinyin: "jīng" },
  { term: "快", pinyin: "kuài" },
  { term: "離", pinyin: "lí" },
  { term: "歷/曆", pinyin: "lì" },
  { term: "球", pinyin: "qiú" },
  { term: "所", pinyin: "suǒ" },
  { term: "聽", pinyin: "tīng" },
  { term: "土", pinyin: "tǔ" },
  { term: "微", pinyin: "wēi" },
  { term: "問", pinyin: "wèn" },
  { term: "夜", pinyin: "yè" },
  { term: "衣", pinyin: "yī、yì", note: "多音字" },
  { term: "議", pinyin: "yì" },
  { term: "總", pinyin: "zǒng" },
  { term: "布", pinyin: "bù" },
  { term: "創", pinyin: "chuàng、chuāng", note: "多音字" },
  { term: "服", pinyin: "fú、fù", note: "多音字" },
  { term: "骨", pinyin: "gǔ、gū", note: "多音字" },
  { term: "官", pinyin: "guān" },
  { term: "極", pinyin: "jí" },
  { term: "舉", pinyin: "jǔ" },
  { term: "決", pinyin: "jué" },
  { term: "科", pinyin: "kē" },
  { term: "禮", pinyin: "lǐ" },
  { term: "亂", pinyin: "luàn" },
  { term: "滿", pinyin: "mǎn" },
  { term: "毛", pinyin: "máo" },
  { term: "破", pinyin: "pò" },
  { term: "器", pinyin: "qì" },
  { term: "輕", pinyin: "qīng" },
  { term: "曲/麯", pinyin: "qū、qǔ（麯僅讀 qū）", note: "多音字" },
  { term: "退", pinyin: "tuì" },
  { term: "溫", pinyin: "wēn" },
  { term: "舞", pinyin: "wǔ" },
  { term: "字", pinyin: "zì" },
  { term: "板/闆", pinyin: "bǎn" },
  { term: "沉", pinyin: "chén" },
  { term: "倒", pinyin: "dǎo、dào", note: "多音字" },
  { term: "等", pinyin: "děng" },
  { term: "費", pinyin: "fèi" },
  { term: "活", pinyin: "huó" },
  { term: "積", pinyin: "jī" },
  { term: "記", pinyin: "jì" },
  { term: "假", pinyin: "jiǎ、jià", note: "多音字" },
  { term: "景", pinyin: "jǐng" },
  { term: "救", pinyin: "jiù" },
  { term: "考", pinyin: "kǎo" },
  { term: "聯", pinyin: "lián" },
  { term: "試", pinyin: "shì" },
  { term: "首", pinyin: "shǒu" },
  { term: "送", pinyin: "sòng" },
  { term: "息", pinyin: "xī" },
  { term: "壓", pinyin: "yā、yà", note: "多音字" },
  { term: "油", pinyin: "yóu" },
  { term: "預", pinyin: "yù" },
  { term: "遠", pinyin: "yuǎn、yuàn", note: "多音字" },
  { term: "筆", pinyin: "bǐ" },
  { term: "差", pinyin: "chā、chà、chāi、cī", note: "多音字" },
  { term: "獨", pinyin: "dú" },
  { term: "額", pinyin: "é" },
  { term: "負", pinyin: "fù" },
  { term: "歌", pinyin: "gē" },
  { term: "激", pinyin: "jī" },
  { term: "境", pinyin: "jìng" },
  { term: "勞", pinyin: "láo" },
  { term: "例", pinyin: "lì" },
  { term: "馬", pinyin: "mǎ" },
  { term: "密", pinyin: "mì" },
  { term: "念", pinyin: "niàn" },
  { term: "設", pinyin: "shè" },
  { term: "示", pinyin: "shì" },
  { term: "投", pinyin: "tóu" },
  { term: "喜", pinyin: "xǐ" },
  { term: "引", pinyin: "yǐn" },
  { term: "院", pinyin: "yuàn" },
  { term: "約", pinyin: "yuē、yāo", note: "多音字" },
  { term: "編", pinyin: "biān" },
  { term: "部", pinyin: "bù" },
  { term: "菜", pinyin: "cài" },
  { term: "參", pinyin: "cān、cēn、shēn", note: "多音字" },
  { term: "到", pinyin: "dào" },
  { term: "古", pinyin: "gǔ" },
  { term: "核", pinyin: "hé、hú", note: "多音字" },
  { term: "靜", pinyin: "jìng" },
  { term: "農", pinyin: "nóng" },
  { term: "射", pinyin: "shè" },
  { term: "私", pinyin: "sī" },
  { term: "素", pinyin: "sù" },
  { term: "速", pinyin: "sù" },
  { term: "隨", pinyin: "suí" },
  { term: "探", pinyin: "tàn" },
  { term: "往", pinyin: "wǎng、wàng", note: "多音字" },
  { term: "細", pinyin: "xì" },
  { term: "象", pinyin: "xiàng" },
  { term: "興", pinyin: "xīng、xìng", note: "多音字" },
  { term: "影", pinyin: "yǐng" },
  { term: "雜", pinyin: "zá" },
  { term: "早", pinyin: "zǎo" },
  { term: "折/摺", pinyin: "折：zhé、shé、zhē；摺：zhé", note: "多音字" },
  { term: "治", pinyin: "zhì" },
  { term: "致/緻", pinyin: "zhì" },
  { term: "足", pinyin: "zú" },
  { term: "半", pinyin: "bàn" },
  { term: "並/併", pinyin: "bìng" },
  { term: "財", pinyin: "cái" },
  { term: "采/採", pinyin: "采：cǎi、cài；採：cǎi", note: "多音字" },
  { term: "超", pinyin: "chāo" },
  { term: "詞", pinyin: "cí" },
  { term: "彈", pinyin: "tán、dàn", note: "多音字" },
  { term: "毒", pinyin: "dú" },
  { term: "規", pinyin: "guī" },
  { term: "覺", pinyin: "jué、jiào", note: "多音字" },
  { term: "局", pinyin: "jú" },
  { term: "刻", pinyin: "kè" },
  { term: "率", pinyin: "lǜ、shuài", note: "多音字" },
  { term: "排", pinyin: "pái、pǎi", note: "多音字" },
  { term: "派", pinyin: "pài、pā", note: "多音字" },
  { term: "盛", pinyin: "shèng、chéng", note: "多音字" },
  { term: "述", pinyin: "shù" },
  { term: "死", pinyin: "sǐ" },
  { term: "態", pinyin: "tài" },
  { term: "談", pinyin: "tán" },
  { term: "王", pinyin: "wáng、wàng", note: "多音字" },
  { term: "寫", pinyin: "xiě、xiè", note: "多音字" },
  { term: "嚴", pinyin: "yán" },
  { term: "遺", pinyin: "yí、wèi", note: "多音字" },
  { term: "營", pinyin: "yíng" },
  { term: "月", pinyin: "yuè" },
  { term: "展", pinyin: "zhǎn" },
  { term: "征/徵", pinyin: "征：zhēng；徵：zhēng、zhǐ", note: "多音字" },
  { term: "整", pinyin: "zhěng" },
  { term: "終", pinyin: "zhōng" },
  { term: "周", pinyin: "zhōu" },
  { term: "暴", pinyin: "bào、pù", note: "多音字" },
  { term: "背", pinyin: "bèi、bēi", note: "多音字" },
  { term: "便", pinyin: "biàn、pián", note: "多音字" },
  { term: "補", pinyin: "bǔ" },
  { term: "測", pinyin: "cè" },
  { term: "層", pinyin: "céng" },
  { term: "初", pinyin: "chū" },
  { term: "船", pinyin: "chuán" },
  { term: "短", pinyin: "duǎn" },
  { term: "兒", pinyin: "ér" },
  { term: "共", pinyin: "gòng" },
  { term: "故", pinyin: "gù" },
  { term: "顧", pinyin: "gù" },
  { term: "寒", pinyin: "hán" },
  { term: "貨", pinyin: "huò" },
  { term: "基", pinyin: "jī" },
  { term: "及", pinyin: "jí" },
  { term: "件", pinyin: "jiàn" },
  { term: "警", pinyin: "jǐng" },
  { term: "就", pinyin: "jiù" },
  { term: "靈", pinyin: "líng" },
  { term: "輪", pinyin: "lún" },
  { term: "迷", pinyin: "mí" },
  { term: "盤", pinyin: "pán" },
  { term: "審", pinyin: "shěn" },
  { term: "市", pinyin: "shì" },
  { term: "順", pinyin: "shùn" },
  { term: "條", pinyin: "tiáo" },
  { term: "停", pinyin: "tíng" },
  { term: "痛", pinyin: "tòng" },
  { term: "脫", pinyin: "tuō" },
  { term: "網", pinyin: "wǎng" },
  { term: "圍", pinyin: "wéi" },
  { term: "像", pinyin: "xiàng" },
  { term: "虛", pinyin: "xū" },
  { term: "煙", pinyin: "yān" },
  { term: "野", pinyin: "yě" },
  { term: "疑", pinyin: "yí" },
  { term: "陰", pinyin: "yīn" },
  { term: "優", pinyin: "yōu" },
  { term: "園", pinyin: "yuán" },
  { term: "源", pinyin: "yuán" },
  { term: "增", pinyin: "zēng" },
  { term: "支", pinyin: "zhī" },
  { term: "助", pinyin: "zhù" },
  { term: "壯", pinyin: "zhuàng" },
];

window.WORD_BANK = [].concat(window.NORMAL_WORDS, window.SPECIAL_WORDS);
